### ISSUE TITLE
Ошибка при распозновании каптчи

### ISSUE THREAD

**Issue by obtim** [DeWizzard/SMS-Bomber#1]
Капча, как картинка, получается. Но при ее вводе получаю ошибку "Поле с номером телефона не корректно" - номер пробовал по разному вводить.

**Comment by DeWizzard** [comment]
Скорее всего ты что то не так делаешь, сначала нужно обновить капчу, ввести ее, а в поле "Номер" ввести номер телефона без спец.символов 
![Screenshot_1](https://user-images.githubusercontent.com/50102128/74082773-6d5eaa80-4a6e-11ea-97e5-9f6b2fe89284.jpg)

**Comment by obtim** [comment]
Да. был уверен, что он хватает номер из левого окна(под Кол-во потоков). Спасибо! Кстати, на гите есть проект **infinite-bomber-reborn** - аналог твоего. Но там больше ресурсов.

**Comment by DeWizzard** [comment]
Знаю, я бы мог улучшать и поддерживать этот бомбер но у меня не особо много времени для этого
