### ISSUE TITLE
How to start the prog?

### ISSUE THREAD

**Issue by newoneb** [DeWizzard/SMS-Bomber#4]

**Comment by newoneb** [comment]
Or how to start the prog? Thanks for any help

**Comment by DeWizzard** [comment]
Run SmsBomber.exe

**Comment by newoneb** [comment]
> Run SmsBomber.exe
So I just download and search it?

**Comment by newoneb** [comment]
> Run SmsBomber.exe

Just redownload the zip and nothing: 
![image](https://user-images.githubusercontent.com/69057502/89507719-91106c80-d7d5-11ea-9a82-2576493b1d11.png)

**Comment by newoneb** [comment]
![image](https://user-images.githubusercontent.com/69057502/89718183-b532a000-d9c5-11ea-872a-c7c1b11cc78d.png)
searched in all, there is no exe

**Comment by ptostochelovek** [comment]
> SmsBomber.exe
